config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :projects do
    resources :todos do
      member do
        put :mark_as_done
        put :assign
      end
    end
  end

  resources :teams

  resources :events

  root to: 'pages#home'
  get "/:page", to: "pages#show"
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
  belongs_to :creator,
    class_name: "User"

  enum status: {
    pending: 0,
    done: 1
  }

  scope :normal, -> { where(deleted_at: nil) }
  scope :deleted, -> { where.not(deleted_at: nil) }

  validates_presence_of :content
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_project
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :mark_as_done, :assign]

  # GET /todos
  # GET /todos.json
  def index
    @filter = params[:status] ||= :pending

    @todos =
      scoped
      .order(created_at: :desc)
      .where(status: params[:status])
      .normal
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = TodoService.create_todo(scope: @project.todos, attrs: todo_params)
    respond_to do |format|
      if @todo.persisted?
        format.html { redirect_to project_todos_path(@project), notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if TodoService.update_todo(@todo, todo_params)
        format.html { redirect_to project_todos_path(@project), notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    TodoService.destroy_todo(@todo)
    respond_to do |format|
      format.html { redirect_to project_todos_url(@project), notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_as_done
    respond_to do |format|
      if TodoService.mark_todo_as_done(@todo)
        format.html { redirect_to project_todos_path(@project), notice: 'Todo was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def assign
    respond_to do |format|
      if TodoService.assign_todo(@todo, assign_params[:assignee_id])
        format.html { redirect_to project_todos_path(@project), notice: 'Todo was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_project
      # TODO should be current_user.projects.find(...)
      @project = Project.find(params[:project_id])
    end

    def scoped
      @project.todos
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:content, :status, :project_id, :creator_id)
    end

    def assign_params
      params.require(:todo).permit(:assignee_id)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_assign_form.html.erb
<%= form_with(model: [:assign, @project, todo], local: true, method: :put) do |form| %>
  <%= form.select :assignee_id, User.pluck(:username, :id) %>
  <%= form.submit "Assign" %>
<% end %>

app/views/todos/_form.html.erb
<%= form_with(model: [@project, todo], local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :todo_content %>
  </div>

  <div class="field">
    <%= form.label :creator_id %>
    <%= form.select :creator_id, User.pluck(:username, :id) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', project_todos_path(@project) %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos - <%= link_to @project.title, project_path(@project) %></h1>

<hr>

<h2>Filter</h2>

<p>Current: <%= params[:status].to_s.humanize %></p>

<% Todo.statuses.each do |key, _value| %>
  <%= link_to key.humanize, project_todos_path(@project, status: key) %>
<% end %>

<hr>

<h2>Content</h2>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Creator</th>
      <th>Assign To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.content %></td>
        <td><%= todo.creator.username %></td>
        <td>
          <%= render "assign_form", todo: todo %>
        </td>
        <td>
          <% if todo.pending? %>
            <%= link_to "Mark as Done", mark_as_done_project_todo_path(@project, todo), method: :put %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_project_todo_path(@project, todo) %></td>
        <td><%= link_to 'Destroy', [@project, todo], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_project_todo_path(@project) %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', project_todos_path(@project) %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<p>
  <strong>Project:</strong>
  <%= @todo.project %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @todo.creator %>
</p>

<%= link_to 'Edit', edit_project_todo_path(@project, @todo) %> |
<%= link_to 'Back', project_todos_path(@project) %>